# Workflow responsible for the 
# major release processes.
#  
# CI/CD Maintainer: Joshua Seals 🦭
#            Email: jseals@renci.org
#

name: Build-Push-Release
on:
  push:
    branches:
      - master 
      - main
    paths-ignore:
      - README.md
      - .old_cicd/*
      # - .github/*
      # - .github/workflows/*
      # - LICENSE
      # - .gitignore
      # - .dockerignore
      # - .githooks
    tags-ignore:
      - 'v[0-9]+.[0-9]+.*'
jobs:
  build-push-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }} 
        fetch-depth: 0

    - name: Set short git commit SHA
      id: vars
      run: |
        echo "short_sha=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
    # https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

    - name: Confirm git commit SHA output
      run: echo ${{ steps.vars.outputs.short_sha }}

    # https://github.com/marketplace/actions/git-semantic-version
    - name: Semver Check
      uses: paulhatch/semantic-version@v5.0.2
      id: version
      with:
        # The prefix to use to identify tags
        tag_prefix: "v"
        # A string which, if present in a git commit, indicates that a change represents a
        # major (breaking) change, supports regular expressions wrapped with '/'
        major_pattern: "/breaking|major|release/"
        # A string which indicates the flags used by the `major_pattern` regular expression. Supported flags: idgs
        major_regexp_flags: "ig"
        # Same as above except indicating a minor change, supports regular expressions wrapped with '/'
        minor_pattern: "/feat|feature|fix/"
        # A string which indicates the flags used by the `minor_pattern` regular expression. Supported flags: idgs
        minor_regexp_flags: "ig"
        # A string to determine the format of the version output
        # version_format: "${major}.${minor}.${patch}-prerelease${increment}"
        version_format: "${major}.${minor}.${patch}"
        search_commit_body: false

    # Note: GITHUB_TOKEN is autogenerated feature of github app
    # which is auto-enabled when using github actions.
    # https://docs.github.com/en/rest/guides/getting-started-with-the-rest-api?apiVersion=2022-11-28#authentication-example-for-github-actions
    - name: Tag New Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG: ${{ steps.version.outputs.version }}
      run: |
        remote=$(git config --get remote.origin.url)
        REPO=$(basename $remote .git)
        curl \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer $GITHUB_TOKEN"\
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/${{ secrets.DOCKERHUB_USERNAME }}/$REPO/git/refs \
        -d '{"ref":"refs/tags/$TAG","sha":"${{ github.sha }}"}'
        
    # Docker Buildx is important to caching in the Build And Push Container
    # step
    # https://github.com/marketplace/actions/build-and-push-docker-images

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Container Registry
      uses: docker/login-action@v2
      with:
        # registry: ${{ secrets.CONTAINER_REGISTRY }}
        # username: ${{ secrets.CONTAINER_USERNAME }}
        # password: ${{ secrets.CONTAINER_TOKEN }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        logout: true

    # Notes on Cache: 
    # https://docs.docker.com/build/ci/github-actions/examples/#inline-cache
    - name: Build Push Container
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: 
          ${{ secrets.DOCKERHUB_USERNAME }}/appstore-testing:v${{ steps.version.outputs.version }}, ${{ secrets.DOCKERHUB_USERNAME }}/appstore-testing:develop, ${{ secrets.DOCKERHUB_USERNAME }}/appstore-testing:${{ steps.vars.outputs.short_sha }}
        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/appstore-testing:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/appstore-testing:buildcache,mode=max



#=======================================================================
    # - name: generate release notes
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   run: |
    #     gh api -X POST 'repos/{owner}/{repo}/releases/generate-notes' \
    #       -F commitish=${{ env.RELEASE_VERSION }} \
    #       -F tag_name=${{ env.RELEASE_VERSION }} \
    #       > tmp-release-notes.json
