name: Build-Push-Release

on:
  push:
    branches:
      - master 
      - main
    # tags:
    #   - 'v[0-9]+.[0-9]+.*'

jobs:
  build-push:
    runs-on: ubuntu-latest
    needs: flake8-check
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0            # fetch the whole repo history

      - name: Git Semver Version
        id: version
        uses: codacy/git-version@2.7.1
        # https://github.com/marketplace/actions/git-version
        env:
          RELEASE_VERSION: v + ${{ steps.version.outputs.version }}
        run: |
          echo ${{ env.RELEASE_VERSION }}

      # - name: generate release notes
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     gh api -X POST 'repos/{owner}/{repo}/releases/generate-notes' \
      #       -F commitish=${{ env.RELEASE_VERSION }} \
      #       -F tag_name=${{ env.RELEASE_VERSION }} \
      #       > tmp-release-notes.json
