# This job depends on flake8 being run first and passing.
name: Test-Build
on:
  pull_request:
    branches:
      - develop
      - master
      - main 
    types: [opened]

jobs:
  test-build:
    needs: flake8-check
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }} 
        # fetch-depth: 0 means, get all branches and commits
        fetch-depth: 0

    - name: Set short git commit SHA
      id: vars
      run: |
        echo "short_sha=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
    # https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

    - name: Confirm git commit SHA output
      run: echo ${{ steps.vars.outputs.short_sha }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Container Registry
      uses: docker/login-action@v2
      with:
        # registry: ${{ secrets.CONTAINER_REGISTRY }}
        # username: ${{ secrets.CONTAINER_USERNAME }}
        # password: ${{ secrets.CONTAINER_TOKEN }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        logout: true

    # Notes on Cache: 
    # https://docs.docker.com/build/ci/github-actions/examples/#inline-cache
    - name: Build Push Container
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/appstore-testing:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/appstore-testing:buildcache,mode=max
